# ------------------------------------------------------------
# Global checkpoint root directory (only change here!)
# ------------------------------------------------------------
paths:
  ckpt_root: "path to /checkpoints"
# ------------------------------------------------------------
# SAM-3 configuration
# ------------------------------------------------------------
sam3:
  ckpt_path: "${paths.ckpt_root}/sam3/sam3.pt"
# ------------------------------------------------------------
# SAM-3D-Body configuration
# ------------------------------------------------------------
sam_3d_body:
  ckpt_path: "${paths.ckpt_root}/sam-3d-body-dinov3/model.ckpt"
  mhr_path: "${paths.ckpt_root}/sam-3d-body-dinov3/assets/mhr_model.pt"
  fov_path: "${paths.ckpt_root}/moge-2-vitl-normal/model.pt"
  batch_size: 64
  detector_path: ""
  segmentor_path: ""
# ------------------------------------------------------------
# Runtime configs
# ------------------------------------------------------------
runtime:
  output_dir: "./outputs"
# ------------------------------------------------------------
# Completion (Diffusion-VAS) configs
# ------------------------------------------------------------
completion:
  enable: true
  detection_resolution: [512, 1024]
  completion_resolution: [512, 1024]
  model_path_mask: "${paths.ckpt_root}/diffusion-vas-amodal-segmentation"
  model_path_rgb: "${paths.ckpt_root}/diffusion-vas-content-completion"
  depth_encoder: "vitl"
  model_path_depth: "${paths.ckpt_root}/dav2"
  max_occ_len: 25
